apiVersion: v2
name: kube-logging
description: A wrapper chat to install Loki and Promtail
type: application
version: 0.1.0

dependencies:
  - name: loki
    version: "^6.16.0"
    repository: https://grafana.github.io/helm-charts
  - name: promtail
    version: "^6.16.6"
    repository: https://grafana.github.io/helm-charts
